services:
  mysql:
  image: mysql-db
  hostname: mysql-db
  networks:
    -arm-mreza
  environment:
    - MYSQL_ROOT_PASSWORD=passsword
    - MYSQL_DATABASE=wt22
  ports:
    -"3306:3306"
wtspirala:
  image: nodejs-app:v1.0
  depends_on:
    - mysql
  networks:
    -arm-mreza
  ports:
    -"3000:3000"
networks:
 arm-mreza:
  name:arm-mreza
command: npm start